// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "megaman":return img`
........................
........................
........................
........................
........................
........................
........................
.....eeee...............
..e.bf..fb.e............
.ee41f..f14ee...........
.ffff.....eef...........
.ddddf444eef............
.....f....f4e...........
.....f....fd4...........
......55..f44...........
........................
........................
........................
........................
........................
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
